import { createPinia } from 'pinia';

export * from './Administration';
export * from './Announcement';
export * from './AppCenter';
export * from './ApplicantType';
export * from './ContactSource';
export * from './ClientSector';
export * from './ContactType';
export * from './Country';
export * from './Currency';
export * from './CommunicationTemplate';
export * from './Gender';
export * from './index';
export * from './NonInsuranceProductType';
export * from './Menu';
export * from './Permission';
export * from './PreferredLanguage';
export * from './PaymentMethods';
export * from './Province';
export * from './Region';
export * from './Role';
export * from './RoleTeam';
export * from './RoleUser';
export * from './Setting';
export * from './ScheduledJob';
export * from './Team';
export * from './TeamRole';
export * from './TeamUser';
export * from './Scope';
export * from './Underwriter';
export * from './User';
export * from './UserTeam';
export * from './UserRole';
export * from './Vendor';

export default createPinia();
