name: Run Unit Tests

on:
    pull_request:
        branches:
            - 0.*.x
    workflow_dispatch:
jobs:
    test:
        name: Run Unit Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                shardIndex: [1, 2, 3, 4]
                shardTotal: [4]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '22'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install --non-interactive --legacy-peer-deps

            - name: Run tests
              run: npx vitest --silent --reporter=dot --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
#            - name: Upload blob report to GitHub Actions Artifacts
#              if: ${{ !cancelled() }}
#              uses: actions/upload-artifact@v4
#              with:
#                  name: blob-report-${{ matrix.shardIndex }}
#                  path: .vitest-reports/*
#                  include-hidden-files: true
#                  retention-days: 1
# it can be enabled when, but we have to change --reporter to something else
#    merge-reports:
#        if: ${{ !cancelled() }}
#        needs: [test]
#
#        runs-on: ubuntu-latest
#        steps:
#            - uses: actions/checkout@v5
#            - name: Set up Node.js
#              uses: actions/setup-node@v6
#              with:
#                  node-version: '22'
#                  cache: 'npm'
#
#            - name: Install dependencies
#              run: npm install --non-interactive --legacy-peer-deps
#
#            - name: Download blob reports from GitHub Actions Artifacts
#              uses: actions/download-artifact@v4
#              with:
#                  path: .vitest-reports
#                  pattern: blob-report-*
#                  merge-multiple: true
#
#            - name: Merge reports
#              run: npx vitest --merge-reports
